aenir3_web/urls.py
from django.contrib import admin
from django.urls import path, include

# import works. nothing to worry about regarding this.
#from aenir.morph import Morph

app_name = "aenir3_web"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("stat_compare/", include("stat_compare.urls")),
    path("chaining", include('smart_selects.urls')),
]

home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("credits/", views.credits, name="credits"),
    path("contact/", views.contact, name="contact"),
]

stat_compare/urls.py
from django.urls import path

from .views import StatCompareViews

app_name = "stat_compare"

urlpatterns = [
    path("", StatCompareViews.index, name="index"),
    path("create/", StatCompareViews.create, name="create"),
    path("edit/", StatCompareViews.edit, name="edit"),
    path("compare/", StatCompareViews.compare, name="compare"),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

def index(request):
    """
    Root of application.
    """
    return render(request, "home/index.html", {})

def about(request):
    return render(request, "home/about.html", {})

def credits(request):
    return render(request, "home/credits.html", {})

def contact(request):
    return render(request, "home/contact.html", {})

home/templates/home/about.html
{% extends 'home/base.jinja' %}
{% block content %}
  <p>about</p>
{% endblock %}

home/templates/home/base.jinja
<!DOCTYPE html>
<html lang="en">
<head>
  <meta>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}">
  <title>aenir - A Fire Emblem stat comparison tool</title>
</head>
<body>

  <div><!-- Clickable header -->
    <h1><!--Intro to what this is-->
      <a href="{% url 'home:index' %}">aenir</a>
    </h1>
  </div>

  <div><!-- Left-hand sidebar -->
    <nav>
      <a href="{% url 'stat_compare:index' %}">Stat Comparison</a>
      <a href="{% url 'home:about' %}">About</a>
      <a href="{% url 'home:credits' %}">Credits</a>
      <a href="{% url 'home:contact' %}">Contact</a>
    </nav>
  <div>

  <div><!-- Canvas where main content goes -->
    {% block content %}
      <!-- Main content here; the stat arrays, the tables, the widgets and junk-->
    {% endblock %}
  </div>

</body>
</html>

home/templates/home/contact.html
{% extends 'home/base.jinja' %}
{% block content %}
  <p>contact</p>
{% endblock %}

home/templates/home/credits.html
{% extends 'home/base.jinja' %}
{% block content %}
  <p>credits</p>
{% endblock %}

home/templates/home/index.html
{% extends 'home/base.jinja' %}
{% block content %}
  <p>index</p>
{% endblock %}