aenir3_web/urls.py
from django.contrib import admin
from django.urls import path, include

# import works. nothing to worry about regarding this.
#from aenir.morph import Morph

app_name = "aenir3_web"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("stat_compare/", include("stat_compare.urls")),
    path("chaining", include('smart_selects.urls')),
]

home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("credits/", views.credits, name="credits"),
    path("contact/", views.contact, name="contact"),
]

stat_compare/urls.py
from django.urls import path

from .views import StatCompareViews

app_name = "stat_compare"

urlpatterns = [
    path("", StatCompareViews.index, name="index"),
    path("create/", StatCompareViews.create, name="create"),
    path("edit/", StatCompareViews.edit, name="edit"),
    path("compare/", StatCompareViews.compare, name="compare"),
]

stat_compare/models.py
from django.db import models
from smart_selects.db_fields import ChainedForeignKey


class FireEmblemGame(models.Model):
    game_num = models.PositiveSmallIntegerField(
        primary_key=True,
        )
    # to NOT be displayed
    game_name = models.CharField(
        unique=True,
        max_length=50,
        )
    display_gamename = models.CharField(
        unique=True,
        max_length=50,
        verbose_name="Game",
        )

    def __str__(self):
        return self.display_gamename


class FireEmblemUnit(models.Model):
    game_num = models.ForeignKey(
        FireEmblemGame,
        on_delete=models.PROTECT,
        )
    unit_name = models.CharField(
        max_length=50,
        #verbose_name="Unit",
        )
    display_unitname = models.CharField(
        max_length=50,
        #verbose_name="Unit",
        )

    def __str__(self):
        return self.display_unitname
        #return str(self.game_num.game_num) + ": " + self.display_unitname


class UnitSelect(models.Model):
    game_num = models.ForeignKey(
        FireEmblemGame,
        on_delete=models.PROTECT,
        verbose_name="Game",
        )
    unit_name = ChainedForeignKey(
        FireEmblemUnit,
        chained_field="game_num",
        chained_model_field="game_num",
        show_all=False,
        sort=False,
        verbose_name="Unit",
        )
    def __str__(self):
        return str(self.game_num) + ": " + self.unit_name.display_unitname

class UserRegistry(models.Model):
    username = models.CharField(
        primary_key=True,
        max_length=50,
        )
    def __str__(self):
        return self.username

class DragonsGate(models.Model):
    username = models.ForeignKey(
        UserRegistry,
        on_delete=models.PROTECT
        )
    game_num = models.PositiveSmallIntegerField(default=0)
    unit_name = models.CharField(max_length=50, default="")
    current_clstype = models.CharField(max_length=50, default="")
    current_cls = models.CharField(max_length=50, default="")
    current_lv = models.PositiveSmallIntegerField(default=0)
    promo_cls = models.CharField(max_length=50, default="")
    bases = models.JSONField(default=dict)
    growths = models.JSONField(default=dict)
    comparison_labels = models.JSONField(default=dict)

# not to be used in forms and so forth

class LyndisLeague(models.Model):
    #game_num = models.PositiveSmallIntegerField( #primary_key=True,)
    unit_name = models.CharField(
        max_length=50,
        primary_key=True,
        )
    display_unitname = models.CharField(
        max_length=50,
        )
    lyn_mode = models.BooleanField(
        default=False,
        verbose_name="Campaign",
        choices=[
            (False, "Main"),
            (True, "Tutorial"),
            ]
        )
    def __str__(self):
        return self.display_unitname

class GenealogyKid(models.Model):
    #game_num = models.PositiveSmallIntegerField( #primary_key=True,)
    unit_name = models.CharField(
        max_length=50,
        primary_key=True,
        )
    display_unitname = models.CharField(
        max_length=50,
        )
    def __str__(self):
        return self.display_unitname

class GenealogyDad(models.Model):
    #game_num = models.PositiveSmallIntegerField( #primary_key=True,)
    father_name = models.CharField(
        max_length=50,
        primary_key=True,
        )
    display_unitname = models.CharField(
        max_length=50,
        )
    def __str__(self):
        return self.display_unitname

stat_compare/views.py
#!/usr/bin/python3
"""
"""

from django.shortcuts import render

from .forms import (
    UnitSelectForm,
    GenealogyDadForm,
    LyndisLeagueForm,
)
from .models import (
    DragonsGate,
    LyndisLeague,
    GenealogyKid,
    GenealogyDad,
    FireEmblemUnit,
)
import aenir.morph


class StatCompareViews:
    """
    """

    # for use in creating Morphs
    QUINTESSENCE = {}

    # for use in Morph methods
    datadir_root = "./stat_compare/static/stat_compare/data/"

    # for use in rendering the web page
    about_unit = {}
    unit_history = {}

    @classmethod
    def _create_new_morph(cls, request):
        # make and save Morph
        game_num = cls.QUINTESSENCE.pop("game_num")
        new_morph = getattr(aenir.morph, "Morph" + str(game_num))(**cls.QUINTESSENCE)
        DragonsGate(
            username=return_username(request),
            game_num=game_num,
            unit_name=cls.QUINTESSENCE["unit_name"],
            current_clstype=new_morph.current_clstype,
            current_cls=new_morph.current_cls,
            current_lv=new_morph.current_lv,
            promo_cls=new_morph.promo_cls,
            bases=new_morph.bases.to_json(),
            growths=new_morph.growths.to_json(),
            comparison_labels=new_morph.comparison_labels,
        ).save()
        # clear QUINTESSENCE
        cls.QUINTESSENCE.clear()
        # redirect to home
        context = {"view_name": ""}
        return render(request, "stat_compare/index.html", context=context)

    @classmethod
    def index(cls, request):
        """
        Contains a compendium of links to the application to access.
        """
        context = {"view_name": ""}
        return render(request, "stat_compare/index.html", context=context)

    @classmethod
    def create(cls, request):
        """
        """
        # 0: (GET request sent)
        # 1: game_num, unit_name
        # 2: select either campaign or dad
        # 3: *
        context = {"view_name": "Create"}
        if request.method == "POST":
            # 1
            try:
                game_num = int(request.POST["game_num"])
                unit_name = FireEmblemUnit.objects.get(pk=int(request.POST["unit_name"][0]))
                QUINTESSENCE.update( {
                    "game_num": game_num,
                    "unit_name": unit_name,
                    }
                )
            except KeyError:
                pass
            # 2
            if "lyn_mode" in request.POST:
                lyn_mode = bool(request.POST["lyn_mode"])
                QUINTESSENCE.update({"lyn_mode": lyn_mode})
                return cls._create_new_morph(cls, request)
            # 2
            elif "father_name" in request.POST:
                father_name = request.POST["father_name"]
                QUINTESSENCE.update({"father_name": father_name})
                return cls._create_new_morph(cls, request)
            else:
                # 1
                skip_fatherselect = False
                try:
                    GenealogyKid.objects.get(unit_name=unit_name)
                    context.update({"form": GenealogyDadForm()})
                except GenealogyKid.DoesNotExist:
                    skip_fatherselect = True
                # 1
                skip_campaignselect = False
                try:
                    LyndisLeague.objects.get(unit_name=unit_name)
                    context.update({"form": LyndisLeagueForm()})
                except LyndisLeague.DoesNotExist:
                    skip_campaignselect = True
                if skip_fatherselect and skip_campaignselect:
                    # redirect to home
                    # make Morph
                    # clear QUINTESSENCE
                    return cls._create_new_morph(cls, request)
        # 0
        else:
            context.update({"form": UnitSelectForm()})
        return render(request, "stat_compare/create.html", context=context)

    @classmethod
    def edit(cls, request):
        """
        """
        context = {"view_name": "Edit"}
        return render(request, "stat_compare/edit.html", context=context)

    @classmethod
    def compare(cls, request):
        """
        """
        context = {"view_name": "Compare"}
        return render(request, "stat_compare/compare.html", context=context)

stat_compare/templates/stat_compare/compare.html
{% extends 'stat_compare/stat_compare.jinja' %}

{% block view_name %}{{ view_name }}{% endblock %}
{% block widget %}{% endblock %}
{% block about_unit %}{% endblock %}
{% block unit_history %}{% endblock %}
{% block stat_table %}
  <p>List Morphs to be compared, select, and then compare to either manual input or compatible existing Morph</p>
{% endblock %}

stat_compare/templates/stat_compare/create.html
{% extends 'stat_compare/stat_compare.jinja' %}

{% block view_name %}{{ view_name }}{% endblock %}
{% block widget %}
<form action="{% url 'stat_compare:create' %}" method="post">
  {% csrf_token %}
  {{ form.media.js }}
  {{ form.as_p }}
  <input type="submit" />
</form>
{% endblock %}

{% block about_unit %}
  {% for label, value in about_table %}
    <tr>
      <th>{{ label }}</th>
      <td>{{ value }}</td>
    </tr>
  {% endfor %}
{% endblock %}
{% block unit_history %}{% endblock %}
{% block stat_table %}
<ul>
  <li>
    Select game; reload
  </li>
  <li>
    Select unit here.
  </li>
  <li>
    Create Morph; load extra options (e.g. Lyn Mode, FE4 fathers) as necessary
  </li>
  <li>
    Confirm selection and junk, or cancel. Create Morph id also.
  </li>
  <li>
    In a later edition, perhaps let user modify stats.
  </li>
</ul>
{% endblock %}

stat_compare/templates/stat_compare/edit.html
{% extends 'stat_compare/stat_compare.jinja' %}

{% block view_name %}{{ view_name }}{% endblock %}
{% block widget %}{% endblock %}
{% block about_unit %}{% endblock %}
{% block unit_history %}{% endblock %}
{% block stat_table %}
  <p>Display list of Morphs to edit, clickable via hyperlink</p>
  <p>Level-Up!Button</p>
  <p>Level-Up!IntegerSelect</p>
  <p>Promote!Button</p>
  <p>Promote!ListboxSelect</p>
  <!-- Defer until all has been finalized.
  <p>Equip Scroll (FE5 only)</p>
  <p>Equip Scroll (FE5 only)</p>
  -->
  <p>Column that shows stat labels</p>
  <p>Column that shows stat values for current stats</p>
  <p>Blank column</p>
  <p>Column that shows increment values</p>
  <p>Blank column</p>
  <p>Column that shows final result of operation</p>
  <p>Section that shows history</p>
{% endblock %}

stat_compare/templates/stat_compare/index.html
{% extends 'stat_compare/stat_compare.jinja' %}

{% block view_name %}{{ view_name }}{% endblock %}
{% block widget %}{% endblock %}
{% block about_unit %}{% endblock %}
{% block unit_history %}{% endblock %}
{% block stat_table %}
  <p>How to use the thing and so forth.</p>
  <p>There may not need to be anything here...</p>
  <p>Put comparison tables here, maybe?</p>
{% endblock %}

stat_compare/templates/stat_compare/stat_compare.jinja
{% extends 'home/base.jinja' %}

{% block content %}

  <div class="left-sidebar">
    <a href="{% url 'stat_compare:create' %}">Create</a>
    <a href="{% url 'stat_compare:edit' %}">Edit</a>
    <a href="{% url 'stat_compare:compare' %}">Compare</a>
  </div>

  <div class="view-name">
    <h2>
      {% block view_name %}{% endblock %}
    </h2>
  </div>

  <div class="widget">
    {% block widget %}{% endblock %}
  </div>

  <div class="about-unit">
    <table>
      <thead>
        <th colspan="2">About</th>
      </thead>
      <tbody>
        {% block about_unit %}{% endblock %}
      </tbody>
    </table>
  </div>

  <div class="unit-history">
    <table>
      <thead>
        <tr>
          <th colspan="2">History</th>
        </tr>
        <tr>
          <th>Lv</th>
          <th>Class</th>
        </tr>
      </thead>
      <tbody>
        {% block unit_history %}{% endblock %}
      </tbody>
    </table>
  </div>

  <div class="stat-table">
    <table>
      {% block stat_table %}{% endblock %}
    </table>
  </div>

{% endblock %}